### PR TITLE
Cav range

### PR DESCRIPTION
**Pull request by gushengjun**

### CODE REVIEW

**Review by kollch — DISMISSED** [review]
On line 52, consider changing to `if x2 - x1 != 0 and y2 - y1 != 0`; it's more clear. Line 50 definitely needs to be changed before merging. Either remove the comment or fix it. There are several spelling errors, and it doesn't make any sense even with them fixed.

**Review by kollch — COMMENTED** [review]
The first commit should not be a part of this branch. It has already been added to the docs branch.

**Comment by gushengjun** [comment]
I have made changes.

**Review by kollch — CHANGES_REQUESTED** [review]
On line 52, the `and` should be changed to `or`. Apologies on last review suggestion.

**Review by kollch — APPROVED** [review]

**Pull request merged**
